---
version: '3.5'

networks:
  nsq:
    name: nsq
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.20.30.0/24

services:
  nsqlookupd:
    image: nsqio/nsq
    container_name: nsqlookupd
    command: /nsqlookupd
    networks:
      - nsq
    ports:
      - 4161:4161

  nsqd:
    image: nsqio/nsq
    container_name: nsqd
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 -broadcast-address=metal-control-plane-nsqd -tls-client-auth-policy=require-verify -tls-root-ca-file=/ca_cert.pem -tls-cert=/client_cert.pem -tls-key=/client_key.pem -tls-required=true
    depends_on:
      - nsqlookupd
    networks:
      - nsq
    volumes:
      - ./certs/ca_cert.pem:/ca_cert.pem
      - ./certs/client_cert.pem:/client_cert.pem
      - ./certs/client_cert-key.pem:/client_key.pem
    ports:
      - 4150:4150
      - 4151:4151
      - 4152:4152

  nsqtest:
    build: .
    image: nsqtest
    container_name: nsqtest
    depends_on:
      - nsqlookupd
      - nsqd
    network_mode: host
    volumes:
      - ./certs/client.pem:/client.pem
      - ./certs/ca_cert.pem:/ca_cert.pem
    extra_hosts:
      - "metal-control-plane-nsqd:10.20.30.1"

  nsqadmin:
    image: nsqio/nsq
    container_name: nsqadmin
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161 -http-client-tls-insecure-skip-verify=false -http-client-tls-root-ca-file=/ca_cert.pem -http-client-tls-cert=/client_cert.pem -http-client-tls-key=/client_key.pem
    depends_on:
      - nsqlookupd
    networks:
      - nsq
    volumes:
      - ./certs/ca_cert.pem:/ca_cert.pem
      - ./certs/client_cert.pem:/client_cert.pem
      - ./certs/client_cert-key.pem:/client_key.pem
    ports:
      - 4171:4171
